
on:
    name: Deploy website on push
    push:
        branches:
        - main
    pull_request:
        branches:
        - main
    jobs:
        deploy:
            name: Deploy
            runs-on: ubuntu-latest
            steps:
            - name: Get latest code
            uses: actions/checkout@v4

            - name: Sync files
            uses: SamKirkland/FTP-Deploy-Action@v4.3.5
            with:
                server: ${{ secrets.MY_FTP_SERVER }}
                username: ${{ secrets.MY_FTP_USERNAME }}
                password: ${{ secrets.MY_FTP_PASSWORD }}
                server-dir: ./codeups/
                local-dir: ./dist/