
name: Deploy website on push

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    ftp-deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Sync files
            uses: SamKirkland/FTP-Deploy-Action@v4.3.0
            with:
                server: ${{ secrets.MY_FTP_SERVER }}
                username: ${{ secrets.MY_FTP_USERNAME }}
                password: ${{ secrets.MY_FTP_PASSWORD }}
                server-dir: ./codeups/
                local-dir: ./dist/